### PR TITLE
Hotfix: Flags were not being propery set on transmitted messages.

### LINKED ISSUE #30: After 4.0.0 release, extended CAN IDs fail to be transmitted
The support team found that, post the 4.0.0 release (including the current 4.0.2 release), extended CAN IDs fail to transmit. This will be addressed ASAP and a new release generated after testing.

### PR DESCRIPTION
**Pull request by JWhitleyAStuff**
Fixes #30.

I was converting the flags returned int in the read() function into a CanMsg but was not setting the flags passed to the write() function _from_ a CanMsg.

### CODE REVIEW

**Comment by jurlaubAStuff** [comment]
How has this been tested?  Are there test cases to cover the changes?

**Comment by JWhitleyAStuff** [comment]
@jurlaubAStuff - I tested it on my local machine using `virtualcan`. I am trying to get test cases set up but having problems with getting `virtualcan` running on the CI machine. See the `maint/ci_read_write_tests` branch on what has been done so far. It might make sense to get that working first.

**Comment by JWhitleyAStuff** [comment]
@jurlaubAStuff - So, what I'm realizing is that there is no way to test these scenarios on CI because of Docker. Docker uses the host's kernel. Because of this, you can't install a kernel module in Docker without some very specific options passed to it when running the Docker container (which we don't have access to pass). I'm going to have to find a way to validate the API without hardware and without virtual channels - unless we stick to running tests only on local machines, which seems to defeat the point. Thoughts?

**Comment by JWhitleyAStuff** [comment]
@jurlaubAStuff - Nevermind. I think I found a way. Stay tuned.

**Comment by JWhitleyAStuff** [comment]
See #33 for tests. In that PR, the tests for extended CAN IDs are disabled due to the bug that this PR fixes. I merged that branch into this one and re-enabled the tests to verify that the bug is fixed.

**Comment by JWhitleyAStuff** [comment]
Actually, #33 is going to take longer than expected as we are going to write and attempt to implement some more detailed test diagnostics. I have verified that this works on Extended CAN IDs and it is passing CI. Can @zoakesAStuff and @jurlaubAStuff please approve if you think it looks alright at this stage so I can get a new release out and fix the bug?

**Comment by zoakesAStuff** [comment]
@JWhitleyAStuff This looks okay, but do we know for sure that it fixes 30?

**Comment by JWhitleyAStuff** [comment]
We will now (just merged CI tests from `maint/ci_read_write_tests` and enabled extended ID testing), at least on the `kvaser_interface` side.

**Comment by JWhitleyAStuff** [comment]
@zoakesAStuff / @jurlaubAStuff - Please approve #37 prior to this PR. That will keep the conflicts to a minimum. Sorry for the confusion.

**Comment by JWhitleyAStuff** [comment]
Approved previously by @zoakesAStuff - merging.

**Pull request merged**
